server:
  host: 0.0.0.0
  port: 12379
# tls:
#   cert: /path/to/file.pem
#   key: /path/to/file.pem

log:
  level: info

datasource:
  type: btree # btree or mysql or sqlite
  # mysql:
  #   host: 127.0.0.1
  #   port: 3306
  #   username: root
  #   password:
  #   database: apisix